Add .travis.yml
alphagov/table_of_contents pull request #2
Opened 2016-12-07 16:03 UTC by thehenster

2016-12-07 16:26 UTC, 36degrees approved these changes

2016-12-07 16:27 UTC, mcmillan commented
I think rather than adding rake, we could just [add a script section to .travis.yml](https://docs.travis-ci.com/user/customizing-the-build#Customizing-the-Build-Step):

```script: bundle exec rspec .```

2016-12-20 01:43 UTC, mcmillan requested changes
See above comment – I don't think a `Rakefile` is necessary.

2016-12-22 13:02 UTC, mcmillan commented
Closing in favour of #3

2016-12-22 13:02 UTC, closed without merging